package com.teamsking.domain.entity.study;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`study_visit`")
public class StudyVisit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.course_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.open_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.unit_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.item_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.item_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.context_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer contextId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.context_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer contextType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.visit_datetime
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer visitDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column study_visit.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.id
     *
     * @return the value of study_visit.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.id
     *
     * @param id the value for study_visit.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.course_id
     *
     * @return the value of study_visit.course_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.course_id
     *
     * @param courseId the value for study_visit.course_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.open_id
     *
     * @return the value of study_visit.open_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.open_id
     *
     * @param openId the value for study_visit.open_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.unit_id
     *
     * @return the value of study_visit.unit_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.unit_id
     *
     * @param unitId the value for study_visit.unit_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.item_id
     *
     * @return the value of study_visit.item_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.item_id
     *
     * @param itemId the value for study_visit.item_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.item_type
     *
     * @return the value of study_visit.item_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.item_type
     *
     * @param itemType the value for study_visit.item_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.context_id
     *
     * @return the value of study_visit.context_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getContextId() {
        return contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.context_id
     *
     * @param contextId the value for study_visit.context_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setContextId(Integer contextId) {
        this.contextId = contextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.user_id
     *
     * @return the value of study_visit.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.user_id
     *
     * @param userId the value for study_visit.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.context_type
     *
     * @return the value of study_visit.context_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getContextType() {
        return contextType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.context_type
     *
     * @param contextType the value for study_visit.context_type
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setContextType(Integer contextType) {
        this.contextType = contextType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.visit_datetime
     *
     * @return the value of study_visit.visit_datetime
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getVisitDatetime() {
        return visitDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.visit_datetime
     *
     * @param visitDatetime the value for study_visit.visit_datetime
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setVisitDatetime(Integer visitDatetime) {
        this.visitDatetime = visitDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.create_id
     *
     * @return the value of study_visit.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.create_id
     *
     * @param createId the value for study_visit.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.create_time
     *
     * @return the value of study_visit.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.create_time
     *
     * @param createTime the value for study_visit.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.update_id
     *
     * @return the value of study_visit.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.update_id
     *
     * @param updateId the value for study_visit.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.update_time
     *
     * @return the value of study_visit.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.update_time
     *
     * @param updateTime the value for study_visit.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column study_visit.delete_status
     *
     * @return the value of study_visit.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column study_visit.delete_status
     *
     * @param deleteStatus the value for study_visit.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}