package com.teamsking.domain.entity.category;

import javax.persistence.*;

@Table(name = "`user_category`")
public class UserCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_category.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_category.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_category.category_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_category.id
     *
     * @return the value of user_category.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_category.id
     *
     * @param id the value for user_category.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_category.user_id
     *
     * @return the value of user_category.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_category.user_id
     *
     * @param userId the value for user_category.user_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_category.category_id
     *
     * @return the value of user_category.category_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_category.category_id
     *
     * @param categoryId the value for user_category.category_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}