package com.teamsking.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`open_set`")
public class OpenSet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.school_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.offline_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer offlinePercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.online_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer onlinePercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.video_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer videoPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.quiz_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer quizPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.assignment_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer assignmentPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.topic_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer topicPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.exam_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer examPercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.video_over
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer videoOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_set.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.id
     *
     * @return the value of open_set.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.id
     *
     * @param id the value for open_set.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.school_id
     *
     * @return the value of open_set.school_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.school_id
     *
     * @param schoolId the value for open_set.school_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.offline_percent
     *
     * @return the value of open_set.offline_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOfflinePercent() {
        return offlinePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.offline_percent
     *
     * @param offlinePercent the value for open_set.offline_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOfflinePercent(Integer offlinePercent) {
        this.offlinePercent = offlinePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.online_percent
     *
     * @return the value of open_set.online_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOnlinePercent() {
        return onlinePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.online_percent
     *
     * @param onlinePercent the value for open_set.online_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOnlinePercent(Integer onlinePercent) {
        this.onlinePercent = onlinePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.video_percent
     *
     * @return the value of open_set.video_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getVideoPercent() {
        return videoPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.video_percent
     *
     * @param videoPercent the value for open_set.video_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setVideoPercent(Integer videoPercent) {
        this.videoPercent = videoPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.quiz_percent
     *
     * @return the value of open_set.quiz_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getQuizPercent() {
        return quizPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.quiz_percent
     *
     * @param quizPercent the value for open_set.quiz_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizPercent(Integer quizPercent) {
        this.quizPercent = quizPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.assignment_percent
     *
     * @return the value of open_set.assignment_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getAssignmentPercent() {
        return assignmentPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.assignment_percent
     *
     * @param assignmentPercent the value for open_set.assignment_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setAssignmentPercent(Integer assignmentPercent) {
        this.assignmentPercent = assignmentPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.topic_percent
     *
     * @return the value of open_set.topic_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getTopicPercent() {
        return topicPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.topic_percent
     *
     * @param topicPercent the value for open_set.topic_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setTopicPercent(Integer topicPercent) {
        this.topicPercent = topicPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.exam_percent
     *
     * @return the value of open_set.exam_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getExamPercent() {
        return examPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.exam_percent
     *
     * @param examPercent the value for open_set.exam_percent
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setExamPercent(Integer examPercent) {
        this.examPercent = examPercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.video_over
     *
     * @return the value of open_set.video_over
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getVideoOver() {
        return videoOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.video_over
     *
     * @param videoOver the value for open_set.video_over
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setVideoOver(Integer videoOver) {
        this.videoOver = videoOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.create_id
     *
     * @return the value of open_set.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.create_id
     *
     * @param createId the value for open_set.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.create_time
     *
     * @return the value of open_set.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.create_time
     *
     * @param createTime the value for open_set.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.update_id
     *
     * @return the value of open_set.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.update_id
     *
     * @param updateId the value for open_set.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.update_time
     *
     * @return the value of open_set.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.update_time
     *
     * @param updateTime the value for open_set.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_set.delete_status
     *
     * @return the value of open_set.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_set.delete_status
     *
     * @param deleteStatus the value for open_set.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}