package com.teamsking.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`quiz_option`")
public class QuizOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.quiz_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer quizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.option_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer optionTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.correct_flag
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer correctFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz_option.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.id
     *
     * @return the value of quiz_option.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.id
     *
     * @param id the value for quiz_option.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.quiz_id
     *
     * @return the value of quiz_option.quiz_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getQuizId() {
        return quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.quiz_id
     *
     * @param quizId the value for quiz_option.quiz_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizId(Integer quizId) {
        this.quizId = quizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.open_id
     *
     * @return the value of quiz_option.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.open_id
     *
     * @param openId the value for quiz_option.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.course_id
     *
     * @return the value of quiz_option.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.course_id
     *
     * @param courseId the value for quiz_option.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.option_title
     *
     * @return the value of quiz_option.option_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOptionTitle() {
        return optionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.option_title
     *
     * @param optionTitle the value for quiz_option.option_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOptionTitle(Integer optionTitle) {
        this.optionTitle = optionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.correct_flag
     *
     * @return the value of quiz_option.correct_flag
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCorrectFlag() {
        return correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.correct_flag
     *
     * @param correctFlag the value for quiz_option.correct_flag
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCorrectFlag(Integer correctFlag) {
        this.correctFlag = correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.create_id
     *
     * @return the value of quiz_option.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.create_id
     *
     * @param createId the value for quiz_option.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.create_time
     *
     * @return the value of quiz_option.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.create_time
     *
     * @param createTime the value for quiz_option.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.update_id
     *
     * @return the value of quiz_option.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.update_id
     *
     * @param updateId the value for quiz_option.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.update_time
     *
     * @return the value of quiz_option.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.update_time
     *
     * @param updateTime the value for quiz_option.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz_option.delete_status
     *
     * @return the value of quiz_option.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz_option.delete_status
     *
     * @param deleteStatus the value for quiz_option.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}