package com.teamsking.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`quiz`")
public class Quiz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.quiz_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String quizTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.quiz_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer quizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.quiz_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String quizAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.difficult_level
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer difficultLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.use_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer useType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.quiz_desc
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String quizDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quiz.quiz_answer
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String quizAnswer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.id
     *
     * @return the value of quiz.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.id
     *
     * @param id the value for quiz.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.open_id
     *
     * @return the value of quiz.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.open_id
     *
     * @param openId the value for quiz.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.course_id
     *
     * @return the value of quiz.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.course_id
     *
     * @param courseId the value for quiz.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.quiz_title
     *
     * @return the value of quiz.quiz_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getQuizTitle() {
        return quizTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.quiz_title
     *
     * @param quizTitle the value for quiz.quiz_title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizTitle(String quizTitle) {
        this.quizTitle = quizTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.quiz_type
     *
     * @return the value of quiz.quiz_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getQuizType() {
        return quizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.quiz_type
     *
     * @param quizType the value for quiz.quiz_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizType(Integer quizType) {
        this.quizType = quizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.quiz_analysis
     *
     * @return the value of quiz.quiz_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getQuizAnalysis() {
        return quizAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.quiz_analysis
     *
     * @param quizAnalysis the value for quiz.quiz_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizAnalysis(String quizAnalysis) {
        this.quizAnalysis = quizAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.difficult_level
     *
     * @return the value of quiz.difficult_level
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDifficultLevel() {
        return difficultLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.difficult_level
     *
     * @param difficultLevel the value for quiz.difficult_level
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDifficultLevel(Integer difficultLevel) {
        this.difficultLevel = difficultLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.use_type
     *
     * @return the value of quiz.use_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.use_type
     *
     * @param useType the value for quiz.use_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUseType(Integer useType) {
        this.useType = useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.create_id
     *
     * @return the value of quiz.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.create_id
     *
     * @param createId the value for quiz.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.create_time
     *
     * @return the value of quiz.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.create_time
     *
     * @param createTime the value for quiz.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.update_id
     *
     * @return the value of quiz.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.update_id
     *
     * @param updateId the value for quiz.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.update_time
     *
     * @return the value of quiz.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.update_time
     *
     * @param updateTime the value for quiz.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.delete_status
     *
     * @return the value of quiz.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.delete_status
     *
     * @param deleteStatus the value for quiz.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.quiz_desc
     *
     * @return the value of quiz.quiz_desc
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getQuizDesc() {
        return quizDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.quiz_desc
     *
     * @param quizDesc the value for quiz.quiz_desc
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizDesc(String quizDesc) {
        this.quizDesc = quizDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quiz.quiz_answer
     *
     * @return the value of quiz.quiz_answer
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getQuizAnswer() {
        return quizAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quiz.quiz_answer
     *
     * @param quizAnswer the value for quiz.quiz_answer
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuizAnswer(String quizAnswer) {
        this.quizAnswer = quizAnswer;
    }
}