package com.teamsking.domain.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`school_friendship`")
public class SchoolFriendship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.school_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.link_name
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.link_order
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer linkOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school_friendship.link_url
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    private String linkUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.id
     *
     * @return the value of school_friendship.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.id
     *
     * @param id the value for school_friendship.id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.school_id
     *
     * @return the value of school_friendship.school_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.school_id
     *
     * @param schoolId the value for school_friendship.school_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.link_name
     *
     * @return the value of school_friendship.link_name
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.link_name
     *
     * @param linkName the value for school_friendship.link_name
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.link_order
     *
     * @return the value of school_friendship.link_order
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getLinkOrder() {
        return linkOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.link_order
     *
     * @param linkOrder the value for school_friendship.link_order
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setLinkOrder(Integer linkOrder) {
        this.linkOrder = linkOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.create_id
     *
     * @return the value of school_friendship.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.create_id
     *
     * @param createId the value for school_friendship.create_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.create_time
     *
     * @return the value of school_friendship.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.create_time
     *
     * @param createTime the value for school_friendship.create_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.update_id
     *
     * @return the value of school_friendship.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.update_id
     *
     * @param updateId the value for school_friendship.update_id
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.update_time
     *
     * @return the value of school_friendship.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.update_time
     *
     * @param updateTime the value for school_friendship.update_time
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.delete_status
     *
     * @return the value of school_friendship.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.delete_status
     *
     * @param deleteStatus the value for school_friendship.delete_status
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school_friendship.link_url
     *
     * @return the value of school_friendship.link_url
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school_friendship.link_url
     *
     * @param linkUrl the value for school_friendship.link_url
     *
     * @mbg.generated Thu Jul 05 21:18:43 CST 2018
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }
}