package com.teamsking.domain.entity.course;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`course_teacher_tag`")
public class CourseTeacherTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.tag_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.course_teacher_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Integer courseTeacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.create_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.create_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.update_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_teacher_tag.update_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.id
     *
     * @return the value of course_teacher_tag.id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.id
     *
     * @param id the value for course_teacher_tag.id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.tag_id
     *
     * @return the value of course_teacher_tag.tag_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.tag_id
     *
     * @param tagId the value for course_teacher_tag.tag_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.course_teacher_id
     *
     * @return the value of course_teacher_tag.course_teacher_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Integer getCourseTeacherId() {
        return courseTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.course_teacher_id
     *
     * @param courseTeacherId the value for course_teacher_tag.course_teacher_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setCourseTeacherId(Integer courseTeacherId) {
        this.courseTeacherId = courseTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.create_id
     *
     * @return the value of course_teacher_tag.create_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.create_id
     *
     * @param createId the value for course_teacher_tag.create_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.create_time
     *
     * @return the value of course_teacher_tag.create_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.create_time
     *
     * @param createTime the value for course_teacher_tag.create_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.update_id
     *
     * @return the value of course_teacher_tag.update_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.update_id
     *
     * @param updateId the value for course_teacher_tag.update_id
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_teacher_tag.update_time
     *
     * @return the value of course_teacher_tag.update_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_teacher_tag.update_time
     *
     * @param updateTime the value for course_teacher_tag.update_time
     *
     * @mbg.generated Sat Jul 28 15:57:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}