package com.teamsking.domain.entity.course;

import java.util.Date;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Table(name = "`course_item`")
public class CourseItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.chapter_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.section_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.item_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.item_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.display_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.relation_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.web_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer webType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.web_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String webName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.web_content
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String webContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.asset_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer assetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_item.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.id
     *
     * @return the value of course_item.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.id
     *
     * @param id the value for course_item.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.chapter_id
     *
     * @return the value of course_item.chapter_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.chapter_id
     *
     * @param chapterId the value for course_item.chapter_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.section_id
     *
     * @return the value of course_item.section_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.section_id
     *
     * @param sectionId the value for course_item.section_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.course_id
     *
     * @return the value of course_item.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.course_id
     *
     * @param courseId the value for course_item.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.item_type
     *
     * @return the value of course_item.item_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.item_type
     *
     * @param itemType the value for course_item.item_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.item_name
     *
     * @return the value of course_item.item_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.item_name
     *
     * @param itemName the value for course_item.item_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.display_order
     *
     * @return the value of course_item.display_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.display_order
     *
     * @param displayOrder the value for course_item.display_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.relation_id
     *
     * @return the value of course_item.relation_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.relation_id
     *
     * @param relationId the value for course_item.relation_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.web_type
     *
     * @return the value of course_item.web_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getWebType() {
        return webType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.web_type
     *
     * @param webType the value for course_item.web_type
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setWebType(Integer webType) {
        this.webType = webType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.web_name
     *
     * @return the value of course_item.web_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getWebName() {
        return webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.web_name
     *
     * @param webName the value for course_item.web_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setWebName(String webName) {
        this.webName = webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.web_content
     *
     * @return the value of course_item.web_content
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getWebContent() {
        return webContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.web_content
     *
     * @param webContent the value for course_item.web_content
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setWebContent(String webContent) {
        this.webContent = webContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.asset_id
     *
     * @return the value of course_item.asset_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.asset_id
     *
     * @param assetId the value for course_item.asset_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.create_id
     *
     * @return the value of course_item.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.create_id
     *
     * @param createId the value for course_item.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.create_time
     *
     * @return the value of course_item.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.create_time
     *
     * @param createTime the value for course_item.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.update_id
     *
     * @return the value of course_item.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.update_id
     *
     * @param updateId the value for course_item.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.update_time
     *
     * @return the value of course_item.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.update_time
     *
     * @param updateTime the value for course_item.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_item.delete_status
     *
     * @return the value of course_item.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_item.delete_status
     *
     * @param deleteStatus the value for course_item.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}
