package com.teamsking.domain.entity.course;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`user_course`")
public class UserCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.user_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.course_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.create_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.create_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.update_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course.update_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    private Integer updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.id
     *
     * @return the value of user_course.id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.id
     *
     * @param id the value for user_course.id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.user_id
     *
     * @return the value of user_course.user_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.user_id
     *
     * @param userId the value for user_course.user_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.course_id
     *
     * @return the value of user_course.course_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.course_id
     *
     * @param courseId the value for user_course.course_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.create_time
     *
     * @return the value of user_course.create_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.create_time
     *
     * @param createTime the value for user_course.create_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.create_id
     *
     * @return the value of user_course.create_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.create_id
     *
     * @param createId the value for user_course.create_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.update_time
     *
     * @return the value of user_course.update_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.update_time
     *
     * @param updateTime the value for user_course.update_time
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course.update_id
     *
     * @return the value of user_course.update_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course.update_id
     *
     * @param updateId the value for user_course.update_id
     *
     * @mbg.generated Tue Jul 31 16:51:24 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }
}