package com.teamsking.domain.entity.sys;

import javax.persistence.*;

@Table(name = "`user_student_assignment`")
public class UserStudentAssignment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_assignment.id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_assignment.user_student_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    private Integer userStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_assignment.assignment_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    private Integer assignmentId;

    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_assignment.id
     *
     * @return the value of user_student_assignment.id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_assignment.id
     *
     * @param id the value for user_student_assignment.id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_assignment.user_student_id
     *
     * @return the value of user_student_assignment.user_student_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public Integer getUserStudentId() {
        return userStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_assignment.user_student_id
     *
     * @param userStudentId the value for user_student_assignment.user_student_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public void setUserStudentId(Integer userStudentId) {
        this.userStudentId = userStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_assignment.assignment_id
     *
     * @return the value of user_student_assignment.assignment_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public Integer getAssignmentId() {
        return assignmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_assignment.assignment_id
     *
     * @param assignmentId the value for user_student_assignment.assignment_id
     *
     * @mbg.generated Fri Aug 17 17:06:22 CST 2018
     */
    public void setAssignmentId(Integer assignmentId) {
        this.assignmentId = assignmentId;
    }

    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}