package com.teamsking.domain.entity.sys;

import javax.persistence.*;

@Table(name = "`user_student_test`")
public class UserStudentTest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_test.id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_test.delete_status
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_test.user_student_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    private Integer userStudentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_student_test.test_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    private Integer testId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_test.id
     *
     * @return the value of user_student_test.id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_test.id
     *
     * @param id the value for user_student_test.id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_test.delete_status
     *
     * @return the value of user_student_test.delete_status
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_test.delete_status
     *
     * @param deleteStatus the value for user_student_test.delete_status
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_test.user_student_id
     *
     * @return the value of user_student_test.user_student_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public Integer getUserStudentId() {
        return userStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_test.user_student_id
     *
     * @param userStudentId the value for user_student_test.user_student_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public void setUserStudentId(Integer userStudentId) {
        this.userStudentId = userStudentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_student_test.test_id
     *
     * @return the value of user_student_test.test_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_student_test.test_id
     *
     * @param testId the value for user_student_test.test_id
     *
     * @mbg.generated Sat Aug 18 15:47:36 CST 2018
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }
}