package com.teamsking.domain.entity.sys;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`user_teacher_group`")
public class UserTeacherGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.group_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.user_teacher_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Integer userTeacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.create_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.create_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.update_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher_group.update_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    private Integer updateId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.id
     *
     * @return the value of user_teacher_group.id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.id
     *
     * @param id the value for user_teacher_group.id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.group_id
     *
     * @return the value of user_teacher_group.group_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.group_id
     *
     * @param groupId the value for user_teacher_group.group_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.user_teacher_id
     *
     * @return the value of user_teacher_group.user_teacher_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Integer getUserTeacherId() {
        return userTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.user_teacher_id
     *
     * @param userTeacherId the value for user_teacher_group.user_teacher_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setUserTeacherId(Integer userTeacherId) {
        this.userTeacherId = userTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.create_time
     *
     * @return the value of user_teacher_group.create_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.create_time
     *
     * @param createTime the value for user_teacher_group.create_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.create_id
     *
     * @return the value of user_teacher_group.create_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.create_id
     *
     * @param createId the value for user_teacher_group.create_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.update_time
     *
     * @return the value of user_teacher_group.update_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.update_time
     *
     * @param updateTime the value for user_teacher_group.update_time
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher_group.update_id
     *
     * @return the value of user_teacher_group.update_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher_group.update_id
     *
     * @param updateId the value for user_teacher_group.update_id
     *
     * @mbg.generated Tue Aug 14 11:40:29 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }
}