package com.teamsking.domain.entity.open;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`open_assignment`")
public class OpenAssignment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.diaplay_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer diaplayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.start_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.end_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.publish_socre_days
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer publishSocreDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.body
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assignment.score
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.id
     *
     * @return the value of open_assignment.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.id
     *
     * @param id the value for open_assignment.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.open_id
     *
     * @return the value of open_assignment.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.open_id
     *
     * @param openId the value for open_assignment.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.course_id
     *
     * @return the value of open_assignment.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.course_id
     *
     * @param courseId the value for open_assignment.course_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.title
     *
     * @return the value of open_assignment.title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.title
     *
     * @param title the value for open_assignment.title
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.diaplay_order
     *
     * @return the value of open_assignment.diaplay_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDiaplayOrder() {
        return diaplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.diaplay_order
     *
     * @param diaplayOrder the value for open_assignment.diaplay_order
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDiaplayOrder(Integer diaplayOrder) {
        this.diaplayOrder = diaplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.status
     *
     * @return the value of open_assignment.status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.status
     *
     * @param status the value for open_assignment.status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.create_id
     *
     * @return the value of open_assignment.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.create_id
     *
     * @param createId the value for open_assignment.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.create_time
     *
     * @return the value of open_assignment.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.create_time
     *
     * @param createTime the value for open_assignment.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.update_id
     *
     * @return the value of open_assignment.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.update_id
     *
     * @param updateId the value for open_assignment.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.update_time
     *
     * @return the value of open_assignment.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.update_time
     *
     * @param updateTime the value for open_assignment.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.delete_status
     *
     * @return the value of open_assignment.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.delete_status
     *
     * @param deleteStatus the value for open_assignment.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.start_time
     *
     * @return the value of open_assignment.start_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.start_time
     *
     * @param startTime the value for open_assignment.start_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.end_time
     *
     * @return the value of open_assignment.end_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.end_time
     *
     * @param endTime the value for open_assignment.end_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.publish_socre_days
     *
     * @return the value of open_assignment.publish_socre_days
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getPublishSocreDays() {
        return publishSocreDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.publish_socre_days
     *
     * @param publishSocreDays the value for open_assignment.publish_socre_days
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setPublishSocreDays(Integer publishSocreDays) {
        this.publishSocreDays = publishSocreDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.body
     *
     * @return the value of open_assignment.body
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.body
     *
     * @param body the value for open_assignment.body
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assignment.score
     *
     * @return the value of open_assignment.score
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assignment.score
     *
     * @param score the value for open_assignment.score
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setScore(String score) {
        this.score = score;
    }
}