package com.teamsking.domain.entity.open;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`open_assistant`")
public class OpenAssistant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.user_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.user_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.course_information
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseInformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.resource_library
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer resourceLibrary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.statistical_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer statisticalAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.curriculum_forum
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer curriculumForum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.class_attribute
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer classAttribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.lecture_notes
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer lectureNotes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.cover_flowe
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer coverFlowe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.teacher_team
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer teacherTeam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.local_teachers
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer localTeachers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.courseware
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer courseware;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.column
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer column;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.notice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer notice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.resource_uploading
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer resourceUploading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.assistant
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer assistant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.student
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.group
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.objective_practice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer objectivePractice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.subjective_exercise
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer subjectiveExercise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.class_discussion
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer classDiscussion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.discussion_area
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer discussionArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.questionnaire
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer questionnaire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.online_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer onlineExamination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.online_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer onlineAchievement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.comprehensive_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer comprehensiveAchievement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.fine_performance
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer finePerformance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.close_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer closeCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.Issuing_certificates
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer issuingCertificates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.progress_survey
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer progressSurvey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.analysis_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer analysisCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.learning_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer learningAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.teaching_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer teachingAnalysis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.release_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer releaseCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.export_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer exportCourse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.under_line_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer underLineExamination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_assistant.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.id
     *
     * @return the value of open_assistant.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.id
     *
     * @param id the value for open_assistant.id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.open_id
     *
     * @return the value of open_assistant.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.open_id
     *
     * @param openId the value for open_assistant.open_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.user_id
     *
     * @return the value of open_assistant.user_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.user_id
     *
     * @param userId the value for open_assistant.user_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.user_name
     *
     * @return the value of open_assistant.user_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.user_name
     *
     * @param userName the value for open_assistant.user_name
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.course_information
     *
     * @return the value of open_assistant.course_information
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseInformation() {
        return courseInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.course_information
     *
     * @param courseInformation the value for open_assistant.course_information
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseInformation(Integer courseInformation) {
        this.courseInformation = courseInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.resource_library
     *
     * @return the value of open_assistant.resource_library
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getResourceLibrary() {
        return resourceLibrary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.resource_library
     *
     * @param resourceLibrary the value for open_assistant.resource_library
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setResourceLibrary(Integer resourceLibrary) {
        this.resourceLibrary = resourceLibrary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.statistical_analysis
     *
     * @return the value of open_assistant.statistical_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getStatisticalAnalysis() {
        return statisticalAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.statistical_analysis
     *
     * @param statisticalAnalysis the value for open_assistant.statistical_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setStatisticalAnalysis(Integer statisticalAnalysis) {
        this.statisticalAnalysis = statisticalAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.curriculum_forum
     *
     * @return the value of open_assistant.curriculum_forum
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCurriculumForum() {
        return curriculumForum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.curriculum_forum
     *
     * @param curriculumForum the value for open_assistant.curriculum_forum
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCurriculumForum(Integer curriculumForum) {
        this.curriculumForum = curriculumForum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.class_attribute
     *
     * @return the value of open_assistant.class_attribute
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getClassAttribute() {
        return classAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.class_attribute
     *
     * @param classAttribute the value for open_assistant.class_attribute
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setClassAttribute(Integer classAttribute) {
        this.classAttribute = classAttribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.lecture_notes
     *
     * @return the value of open_assistant.lecture_notes
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getLectureNotes() {
        return lectureNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.lecture_notes
     *
     * @param lectureNotes the value for open_assistant.lecture_notes
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setLectureNotes(Integer lectureNotes) {
        this.lectureNotes = lectureNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.cover_flowe
     *
     * @return the value of open_assistant.cover_flowe
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCoverFlowe() {
        return coverFlowe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.cover_flowe
     *
     * @param coverFlowe the value for open_assistant.cover_flowe
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCoverFlowe(Integer coverFlowe) {
        this.coverFlowe = coverFlowe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.teacher_team
     *
     * @return the value of open_assistant.teacher_team
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getTeacherTeam() {
        return teacherTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.teacher_team
     *
     * @param teacherTeam the value for open_assistant.teacher_team
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setTeacherTeam(Integer teacherTeam) {
        this.teacherTeam = teacherTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.local_teachers
     *
     * @return the value of open_assistant.local_teachers
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getLocalTeachers() {
        return localTeachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.local_teachers
     *
     * @param localTeachers the value for open_assistant.local_teachers
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setLocalTeachers(Integer localTeachers) {
        this.localTeachers = localTeachers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.courseware
     *
     * @return the value of open_assistant.courseware
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCourseware() {
        return courseware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.courseware
     *
     * @param courseware the value for open_assistant.courseware
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCourseware(Integer courseware) {
        this.courseware = courseware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.column
     *
     * @return the value of open_assistant.column
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getColumn() {
        return column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.column
     *
     * @param column the value for open_assistant.column
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setColumn(Integer column) {
        this.column = column;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.notice
     *
     * @return the value of open_assistant.notice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.notice
     *
     * @param notice the value for open_assistant.notice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setNotice(Integer notice) {
        this.notice = notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.resource_uploading
     *
     * @return the value of open_assistant.resource_uploading
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getResourceUploading() {
        return resourceUploading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.resource_uploading
     *
     * @param resourceUploading the value for open_assistant.resource_uploading
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setResourceUploading(Integer resourceUploading) {
        this.resourceUploading = resourceUploading;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.assistant
     *
     * @return the value of open_assistant.assistant
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getAssistant() {
        return assistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.assistant
     *
     * @param assistant the value for open_assistant.assistant
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setAssistant(Integer assistant) {
        this.assistant = assistant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.student
     *
     * @return the value of open_assistant.student
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getStudent() {
        return student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.student
     *
     * @param student the value for open_assistant.student
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setStudent(Integer student) {
        this.student = student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.group
     *
     * @return the value of open_assistant.group
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.group
     *
     * @param group the value for open_assistant.group
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setGroup(Integer group) {
        this.group = group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.objective_practice
     *
     * @return the value of open_assistant.objective_practice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getObjectivePractice() {
        return objectivePractice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.objective_practice
     *
     * @param objectivePractice the value for open_assistant.objective_practice
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setObjectivePractice(Integer objectivePractice) {
        this.objectivePractice = objectivePractice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.subjective_exercise
     *
     * @return the value of open_assistant.subjective_exercise
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getSubjectiveExercise() {
        return subjectiveExercise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.subjective_exercise
     *
     * @param subjectiveExercise the value for open_assistant.subjective_exercise
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setSubjectiveExercise(Integer subjectiveExercise) {
        this.subjectiveExercise = subjectiveExercise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.class_discussion
     *
     * @return the value of open_assistant.class_discussion
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getClassDiscussion() {
        return classDiscussion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.class_discussion
     *
     * @param classDiscussion the value for open_assistant.class_discussion
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setClassDiscussion(Integer classDiscussion) {
        this.classDiscussion = classDiscussion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.discussion_area
     *
     * @return the value of open_assistant.discussion_area
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDiscussionArea() {
        return discussionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.discussion_area
     *
     * @param discussionArea the value for open_assistant.discussion_area
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDiscussionArea(Integer discussionArea) {
        this.discussionArea = discussionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.questionnaire
     *
     * @return the value of open_assistant.questionnaire
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getQuestionnaire() {
        return questionnaire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.questionnaire
     *
     * @param questionnaire the value for open_assistant.questionnaire
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setQuestionnaire(Integer questionnaire) {
        this.questionnaire = questionnaire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.online_examination
     *
     * @return the value of open_assistant.online_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOnlineExamination() {
        return onlineExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.online_examination
     *
     * @param onlineExamination the value for open_assistant.online_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOnlineExamination(Integer onlineExamination) {
        this.onlineExamination = onlineExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.online_achievement
     *
     * @return the value of open_assistant.online_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getOnlineAchievement() {
        return onlineAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.online_achievement
     *
     * @param onlineAchievement the value for open_assistant.online_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setOnlineAchievement(Integer onlineAchievement) {
        this.onlineAchievement = onlineAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.comprehensive_achievement
     *
     * @return the value of open_assistant.comprehensive_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getComprehensiveAchievement() {
        return comprehensiveAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.comprehensive_achievement
     *
     * @param comprehensiveAchievement the value for open_assistant.comprehensive_achievement
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setComprehensiveAchievement(Integer comprehensiveAchievement) {
        this.comprehensiveAchievement = comprehensiveAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.fine_performance
     *
     * @return the value of open_assistant.fine_performance
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getFinePerformance() {
        return finePerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.fine_performance
     *
     * @param finePerformance the value for open_assistant.fine_performance
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setFinePerformance(Integer finePerformance) {
        this.finePerformance = finePerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.close_course
     *
     * @return the value of open_assistant.close_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCloseCourse() {
        return closeCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.close_course
     *
     * @param closeCourse the value for open_assistant.close_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCloseCourse(Integer closeCourse) {
        this.closeCourse = closeCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.Issuing_certificates
     *
     * @return the value of open_assistant.Issuing_certificates
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getIssuingCertificates() {
        return issuingCertificates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.Issuing_certificates
     *
     * @param issuingCertificates the value for open_assistant.Issuing_certificates
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setIssuingCertificates(Integer issuingCertificates) {
        this.issuingCertificates = issuingCertificates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.progress_survey
     *
     * @return the value of open_assistant.progress_survey
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getProgressSurvey() {
        return progressSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.progress_survey
     *
     * @param progressSurvey the value for open_assistant.progress_survey
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setProgressSurvey(Integer progressSurvey) {
        this.progressSurvey = progressSurvey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.analysis_course
     *
     * @return the value of open_assistant.analysis_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getAnalysisCourse() {
        return analysisCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.analysis_course
     *
     * @param analysisCourse the value for open_assistant.analysis_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setAnalysisCourse(Integer analysisCourse) {
        this.analysisCourse = analysisCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.learning_analysis
     *
     * @return the value of open_assistant.learning_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getLearningAnalysis() {
        return learningAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.learning_analysis
     *
     * @param learningAnalysis the value for open_assistant.learning_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setLearningAnalysis(Integer learningAnalysis) {
        this.learningAnalysis = learningAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.teaching_analysis
     *
     * @return the value of open_assistant.teaching_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getTeachingAnalysis() {
        return teachingAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.teaching_analysis
     *
     * @param teachingAnalysis the value for open_assistant.teaching_analysis
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setTeachingAnalysis(Integer teachingAnalysis) {
        this.teachingAnalysis = teachingAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.release_course
     *
     * @return the value of open_assistant.release_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getReleaseCourse() {
        return releaseCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.release_course
     *
     * @param releaseCourse the value for open_assistant.release_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setReleaseCourse(Integer releaseCourse) {
        this.releaseCourse = releaseCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.export_course
     *
     * @return the value of open_assistant.export_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getExportCourse() {
        return exportCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.export_course
     *
     * @param exportCourse the value for open_assistant.export_course
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setExportCourse(Integer exportCourse) {
        this.exportCourse = exportCourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.under_line_examination
     *
     * @return the value of open_assistant.under_line_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUnderLineExamination() {
        return underLineExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.under_line_examination
     *
     * @param underLineExamination the value for open_assistant.under_line_examination
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUnderLineExamination(Integer underLineExamination) {
        this.underLineExamination = underLineExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.create_id
     *
     * @return the value of open_assistant.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.create_id
     *
     * @param createId the value for open_assistant.create_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.create_time
     *
     * @return the value of open_assistant.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.create_time
     *
     * @param createTime the value for open_assistant.create_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.update_id
     *
     * @return the value of open_assistant.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.update_id
     *
     * @param updateId the value for open_assistant.update_id
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.update_time
     *
     * @return the value of open_assistant.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.update_time
     *
     * @param updateTime the value for open_assistant.update_time
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_assistant.delete_status
     *
     * @return the value of open_assistant.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_assistant.delete_status
     *
     * @param deleteStatus the value for open_assistant.delete_status
     *
     * @mbg.generated Tue Jun 26 17:08:40 CST 2018
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}