package com.teamsking.domain.entity.open;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`user_open`")
public class UserOpen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.user_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.open_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Integer openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.create_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Integer createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.create_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.update_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Integer updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_open.update_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.id
     *
     * @return the value of user_open.id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.id
     *
     * @param id the value for user_open.id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.user_id
     *
     * @return the value of user_open.user_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.user_id
     *
     * @param userId the value for user_open.user_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.open_id
     *
     * @return the value of user_open.open_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Integer getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.open_id
     *
     * @param openId the value for user_open.open_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setOpenId(Integer openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.create_id
     *
     * @return the value of user_open.create_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.create_id
     *
     * @param createId the value for user_open.create_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.create_time
     *
     * @return the value of user_open.create_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.create_time
     *
     * @param createTime the value for user_open.create_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.update_id
     *
     * @return the value of user_open.update_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.update_id
     *
     * @param updateId the value for user_open.update_id
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_open.update_time
     *
     * @return the value of user_open.update_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_open.update_time
     *
     * @param updateTime the value for user_open.update_time
     *
     * @mbg.generated Tue Aug 07 18:34:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}